services:
  client:
    container_name: client
    image: ghcr.io/linkinlog/throttlr-client:latest
    restart: always
    ports:
      - "8090:8080"
    environment:
      ENV: ${ENV}
      SELF_HOSTED: ${SELF_HOSTED}
      DEBUG: ${DEBUG}
      GITHUB_KEY: ${GITHUB_KEY}
      GITHUB_SECRET: ${GITHUB_SECRET}
      GOOGLE_KEY: ${GOOGLE_KEY}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      CLIENT_DB: ${CLIENT_DB}
      CLIENT_CALLBACK_URL: ${CLIENT_CALLBACK_URL}
      SERVER_CALLBACK_URL: ${SERVER_CALLBACK_URL}
      CLIENT_INTERNAL_URL: ${CLIENT_INTERNAL_URL}
      SERVER_INTERNAL_URL: ${SERVER_INTERNAL_URL}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    networks:
      - throttlr
  server:
    container_name: server
    image: ghcr.io/linkinlog/throttlr-server:latest
    restart: always
    ports:
      - "8091:8081"
    environment:
      ENV: ${ENV}
      SELF_HOSTED: ${SELF_HOSTED}
      DEBUG: ${DEBUG}
      SESSION_SECRET: ${SESSION_SECRET}
      SERVER_DB: ${SERVER_DB}
      CLIENT_CALLBACK_URL: ${CLIENT_CALLBACK_URL}
      SERVER_CALLBACK_URL: ${SERVER_CALLBACK_URL}
      CLIENT_INTERNAL_URL: ${CLIENT_INTERNAL_URL}
      SERVER_INTERNAL_URL: ${SERVER_INTERNAL_URL}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    networks:
      - throttlr
  db:
    container_name: db
    image: postgres
    restart: always
    shm_size: 128mb
    user: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: throttlr
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./build:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 10
    networks:
      - throttlr
volumes:
  db-data:
networks:
  throttlr:
    driver: bridge
