// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"github.com/linkinlog/throttlr/internal/models"
	"github.com/linkinlog/throttlr/web/partials"
	"github.com/linkinlog/throttlr/web/shared"
)

func NewDashboard(endpoints []*models.Endpoint, key string) dashboard {
	return dashboard{
		endpoints: endpoints,
		key:       key,
	}
}

type dashboard struct {
	endpoints []*models.Endpoint
	key       string
}

func (d dashboard) Props() shared.PageProps {
	return shared.PageProps{
		Title: "Dashboard",
	}
}

func (d dashboard) View() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"mt-4\"><a href=\"/endpoints\" hx-get=\"/endpoints\" hx-replace-url=\"/endpoints\" hx-select=\"main\" hx-target=\"main\" hx-swap=\"outerHTML\"><button class=\"bg-primary text-dark rounded-lg w-12 h-12 text-4xl font-extralight relative floaty\">+</button></a></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(d.endpoints) == 0 {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<p class=\"text-center text-secondary\">No endpoints registered.</p><p class=\"text-center text-secondary\">Click the + button to register a new endpoint and get started!</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = partials.Endpoints(d.endpoints, d.key).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
