// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/linkinlog/throttlr/internal/models"
	"github.com/linkinlog/throttlr/web/partials"
	"github.com/linkinlog/throttlr/web/shared"
)

func NewDashboard(endpoints []*models.Endpoint, key string) dashboard {
	return dashboard{
		endpoints: endpoints,
		key:       key,
	}
}

type dashboard struct {
	endpoints []*models.Endpoint
	key       string
}

func (d dashboard) Props() shared.PageProps {
	return shared.PageProps{
		Title: "Dashboard",
	}
}

func (d dashboard) View() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"mt-4\"><a href=\"/endpoints\" hx-get=\"/endpoints\" hx-replace-url=\"/endpoints\" hx-select=\"main\" hx-target=\"main\" hx-swap=\"outerHTML\"><button class=\"bg-primary text-dark rounded-lg w-12 h-12 text-4xl font-extralight relative floaty\">+</button></a></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(d.endpoints) == 0 {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<p class=\"text-center text-secondary\">No endpoints registered.</p><p class=\"text-center text-secondary\">Click the + button to register a new endpoint and get started!</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = partials.Endpoints(d.endpoints, d.key).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
