// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package shared

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func stylesMap() map[templ.CSSClass]struct{} {
	return map[templ.CSSClass]struct{}{}
}

func Styles() []templ.CSSClass {
	m := stylesMap()
	s := make([]templ.CSSClass, 0, len(m))
	for k := range m {
		s = append(s, k)
	}
	return s
}
